config/routes.rb
Rails.application.routes.draw do
  get root :to => 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:create, :show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"

    def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
    end

    def guest_user?
      email == GUEST_USER_EMAIL
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_detail = Book.find(params[:id])
    @user = User.find(@book_detail.user_id)
    @book = Book.new
  end

  def edit
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all
  end

  def edit
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if book.errors.any? %>
  <h3><%= book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/_user_info_new_book.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tbody>
    <tr>
      <td class="font-weight-bold">name</td>
      <td class="font-weight-bold"><%= user.name %></td>
    </tr>
    <tr>
      <td class="font-weight-bold">introduction</td>
      <td class="font-weight-bold"><%= user.introduction %></td>
    </tr>
  </tbody>
</table>
<p>
  <%= link_to edit_user_path(user.id), class:'btn btn-outline-secondary btn-block' do %>
  <i class="fa-solid fa-user-gear"></i>
  <% end %>
</p>

<h2>New book</h2>
<%= form_with model: @book do |f| %>
  <label for="book_title" class="form-label">Title</label>
  <%= f.text_field :title, class: 'form-control' %>
  <label for="book_body" class="form-label">Opinion</label>
  <%= f.text_area :body, class: 'form-control' %><br>
  <%= f.submit 'Create Book', class:'btn btn-success' %>
<% end %>

app/views/books/_userinfo_newbook.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tbody>
    <tr>
      <td class="font-weight-bold">name</td>
      <td class="font-weight-bold"><%= user.name %></td>
    </tr>
    <tr>
      <td class="font-weight-bold">introduction</td>
      <td class="font-weight-bold"><%= user.introduction %></td>
    </tr>
  </tbody>
</table>
<% unless user.guest_user? %>
<div class="row", style="margin-top: 40px;">
  <%= link_to edit_user_path(user), class:'btn btn-outline-secondary btn-block' do %>
  <i class="fa-solid fa-user-cog"></i>
  <% end %>
</div>
<% end %>

<h2 class="mt-3 mb-2">New book</h2>
<%= form_with model: @book do |f| %>
  <div class="form-box mb-3">
    <label for="book_title" class="form-label">Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-box mb-3">
    <label for="book_body" class="form-label">Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-box mb-3">
    <%= f.submit 'Create Book', class:'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'error', book: @book %>
      <%= form_with model: @book do |f| %>
        <div class=" form-box mb-3">
          <label for="book_title" class="form-label">Title</label>
          <%= f.text_field :title, id: "book_title", class: 'form-control' %>
        </div>
        <div class="form-box mb-3">
          <label for="book_body" class="form-label">Opinion</label>
          <%= f.text_area :body, id: "book_body", class: 'form-control' %>
        </div>
        <div class="form-box mb-3">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
      <% end %>
        <%= link_to 'Show', book_path(@book.id) %> | <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'error', book: @book %>
  <div class="row">
    <div class="index-left col-md-3">
      <%= render 'userinfo_newbook', user: @user %>
    </div>
    <div class="index-right col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover ">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="book-show-left col-md-3">
      <%= render 'userinfo_newbook', user: @user %>
    </div>
    <div class="book-show-right col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @book_detail.user.get_profile_image(100, 100) %><br>
                <%= @book_detail.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book_detail.id) do %>
                <%= @book_detail.title %>
              <% end %>
            </td>
            <td><%= @book_detail.body %></td>
            <% if @book_detail.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book_detail.id), class: 'btn btn-success btn-sm' %></td>
              <td><%= link_to 'Destroy', book_path(@book_detail.id), method: :delete, data:{confirm: '本当に消しますか?'}, class: 'btn btn-danger btn-sm' %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <i class="fa-solid fa-book"></i><b>Bookers</b>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><b>Bookers</b> !!</h1>
      <p>In <i class="fa-solid fa-book"></i><b>Bookers</b>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-box col-10 mx-auto">
        <div class="row mb-3">
          <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, class: 'btn btn-secondary btn-block btn-sm sign_in', method: :post %>
        </div>
        <div class="row mb-3">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-block btn-sm text-white sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-block btn-sm text-white sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4a7905e8fa.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <div class="container">
          <div class="navbar-bland">
            <%= link_to root_path, class: 'text-white lead py-2' do %>
              <span><b>Bookers</b></span>
            <% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-home"></i>
                <%= link_to "Home", user_path(current_user.id), class: 'text-white' %>
              </li>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-users"></i>
                <%= link_to "Users", users_path, class: 'text-white' %>
              </li>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-book-open"></i>
                <%= link_to "Books", books_path, class: 'text-white' %>
              </li>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-sign-out-alt"></i>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'text-white' %>
              </li>
            <% else %>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-home"></i>
                <%= link_to "Home", root_path, class: 'text-white' %>
              </li>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-link"></i>
                <%= link_to "About", home_about_path, class: 'text-white' %>
              </li>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-user-plus"></i>
                <%= link_to "Sign up", new_user_registration_path, class: 'text-white' %>
              </li>
              <li class="navbar-item px-2 py-2">
                <i class="fa-solid fa-sign-in-alt"></i>
                <%= link_to "Log in", new_user_session_path, class: 'text-white' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <div class="<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="main-contents mt-3">
        <%= yield %>
      </div>
    </main>
    <footer class="mt-5">
      <div class="container-fluid">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-box mb-3">
          <label for="user_name", class="form-label">Name</label>
          <%= f.text_field :name, id: "user_name", class: 'form-control' %>
        </div>
        <div class="form-box mb-3">
          <label for="profile_image">Image</label><br>
          <%= f.file_field :profile_image, id: "profile_image", accept: "image/*" %>
        </div>
        <div class="form-box mb-3">
          <label for="introduction">Introduction</label><br>
          <%= f.text_area :introduction, id: "introduction", class: 'form-control' %>
        </div>
        <div class="form-box mb-3">
          <%= f.submit "Update User", class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', book: @book %>
  <div class="row">
    <div class="index-left col-md-3">
      <%= render 'books/userinfo_newbook', user: @user %>
    </div>
    <div class="index-right col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(80, 80) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', book: @book %>
  <div class="row">
    <div class="index-left col-md-3">
      <%= render 'books/userinfo_newbook', user: @user %>
    </div>
    <div class="index-right col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>